# Generated by Django 2.1.5 on 2019-01-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workedYears_min', models.IntegerField(null=True)),
                ('workedYears_max', models.IntegerField(null=True)),
                ('salaryBrutto_min', models.IntegerField(null=True)),
                ('salaryBrutto_max', models.IntegerField(null=True)),
            ],
        ),
    ]
