# Generated by Django 2.1.5 on 2019-01-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_chartrange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartrange',
            old_name='salaryBrutto_max',
            new_name='x_max',
        ),
        migrations.RenameField(
            model_name='chartrange',
            old_name='salaryBrutto_min',
            new_name='x_min',
        ),
        migrations.RenameField(
            model_name='chartrange',
            old_name='workedYears_max',
            new_name='y_max',
        ),
        migrations.RenameField(
            model_name='chartrange',
            old_name='workedYears_min',
            new_name='y_min',
        ),
    ]
