# Generated by Django 2.1.5 on 2019-01-16 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190116_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartrange',
            old_name='x_max',
            new_name='salaryBrutto_max',
        ),
        migrations.RenameField(
            model_name='chartrange',
            old_name='x_min',
            new_name='salaryBrutto_min',
        ),
        migrations.RenameField(
            model_name='chartrange',
            old_name='y_max',
            new_name='workedYears_max',
        ),
        migrations.RenameField(
            model_name='chartrange',
            old_name='y_min',
            new_name='workedYears_min',
        ),
    ]
