# Generated by Django 2.1.5 on 2019-01-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190116_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='test',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
