# Generated by Django 2.1.5 on 2019-01-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_data_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChartRange',
        ),
    ]
